name: Run Simulation

on: [push]

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Icarus Verilog
        run: sudo apt-get install -y iverilog

      - name: Compile and run simulation
        run: |
          cd ai_accelerator_top
          mkdir -p build
          iverilog -o build/sim \
            tb/ai_accelerator_top_tb.v \
            rtl/ai_accelerator_top.v \
            ../controller_fsm/rtl/controller_fsm.v \
            ../systolic_array_2d/rtl/systolic_array_2d.v \
            ../processing_element/rtl/processing_element.v
          vvp build/sim
